### ISSUE TITLE
App does not open on Fedora 38

### ISSUE THREAD

**Issue by Ben7230** [bluecherrydvr/unity#159]
I downloaded the .rpm and installed with sudo dnf install ./ file name.

It installs fine and shows up on in the Application launcher, if i click on it I will get a icon on the task bar for a brief moment and then it goes away.

The .RPM seems to be stuck on version 3.0.0_beta8-1, at least that is what showed up when I went to install it.

I tried the appimage and I got the icon on the task bar and a window starts to open but only for a second and then closes.

**Comment by curtishall** [comment]
Thanks...this should be fixed soon, sounds similar to this bug:

https://github.com/bluecherrydvr/unity/pull/158

**Comment by bdlukaa** [comment]
@Ben7230 Hello! Would you be able to install and try the latest pre-release?

You can download it at https://github.com/bluecherrydvr/unity#download

The issue seem to be fixed but a confirmation would be helpful.

**Comment by Ben7230** [comment]
Are your files actually being updated?  it still shows beta 8-1.


![Screenshot_20230918_1745](https://github.com/bluecherrydvr/unity/assets/97363017/a4c5d39d-702b-48d6-9094-0bdb3738daf0)

**Comment by bdlukaa** [comment]
Nice catch! The version number hasn't been updated for the `.rpm` file: https://github.com/bluecherrydvr/unity/blob/137fd2d2753d3b249dce526050203c83519f3b9c/linux/rpm/bluecherry.spec#L2C24-L2C24. I am coming with a fix in the next hours.

Nevertheless, the version number should not impact the app being installed or not. Can you uninstall it and uninstall it again?

**Comment by Ben7230** [comment]
I do not see any change. 

One note, I am unable install mpv & libmpv-dev, is this only for Debian, or will I need to install it somehow?

**Comment by Ben7230** [comment]
Downloaded and installed the latest version. Same problem as before, I see the icon for a brief moment and then it disappears. 

It now shows the correct version when installing. 

Is there some logs somewhere that might point to the problem its running into.

**Comment by curtishall** [comment]
Are you using beta 12?

**Comment by Ben7230** [comment]
Yes, beta12, the version that was uploaded 2 days ago.

**Comment by curtishall** [comment]
Can you try the latest from here? https://github.com/bluecherrydvr/unity/releases/tag/bleeding_edge

**Comment by Ben7230** [comment]
![image](https://github.com/bluecherrydvr/unity/assets/97363017/cea89d20-194e-448b-9e08-d11f6ed366dc)


Same thing happens. I see the icon for a moment and then it disappears.

**Comment by bdlukaa** [comment]
Unfortunately, we have been having issues with our video player on Fedora. That is the most likely reason why the app doesn't open. See https://github.com/media-kit/media-kit/issues/595

This doesn't seem to have an estimated time to get fixed and any help is appreciated.

**Comment by bdlukaa** [comment]
@Ben7230 Hello! Could you try the latest executable from [bleeding_edge](https://github.com/bluecherrydvr/unity/releases/tag/bleeding_edge)? Also, does the `.AppImage` work on your system as well?

**Comment by bdlukaa** [comment]
Closing this as stale.
